import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  // 手动定义侧边栏，替换自动生成的结构
  tutorialSidebar: [
    'Overview',

    'Contributing',

    {
      type: 'category',
      label: '基础知识',
      link: {
        type: 'doc',
        id: 'Basic-Knowledge/1Overview'
      },
      items: [
        { type: 'autogenerated', dirName: 'Basic-Knowledge' }
      ],
    },
    {
      type: 'category',
      label: '前端',
      link: {
        type: 'doc',
        id: 'Front-End/NodeJsMarkdown'
      },
      items: [
        { type: 'autogenerated', dirName: 'Front-End' }
      ]
    },
    {
      type: 'category',
      label: '后端',
      items: [
        { type: 'autogenerated', dirName: 'Back-End' }
      ]
    },
    {
      type: 'category',
      label: 'AI',
      link: {
        type: 'doc',
        id: 'AI/Stable_Diffusion'
      },
      items: [
        { type: 'autogenerated', dirName: 'AI' }
      ]
    },
    {
      type: 'category',
      label: '运维',
      link: {
        type: 'doc',
        id: 'Operation-and-Maintenance/Shell'
      },
      items: [
        { type: 'autogenerated', dirName: 'Operation-and-Maintenance' }
      ]
    },
    {
      type: 'category',
      label: 'Hacking',
      link: {
        type: 'doc',
        id: 'Hacking/README'
      },
      items: [
        { type: 'autogenerated', dirName: 'Hacking' }
      ]
    },
    {
      type: 'category',
      label: '机器学习',
      link: {
        type: 'doc',
        id: 'Machine-Learning/README'
      },
      items: [
        { type: 'autogenerated', dirName: 'Machine-Learning' }
      ]
    },
    {
      type: 'category',
      label: '量子计算',
      link: {
        type: 'doc',
        id: 'Quantum-Computing/README'
      },
      items: [
        { type: 'autogenerated', dirName: 'Quantum-Computing' }
      ]
    },
    {
      type: 'category',
      label: '其他',
      link: {
        type: 'doc',
        id: 'Other/How_to_Play_Minecraft_server'
      },
      items: [
        { type: 'autogenerated', dirName: 'Other' }
      ]
    },
  ],
};

export default sidebars;
