import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  // 自定义侧边栏:
  // 指定排序 + 自定义名称
  tutorialSidebar: [
    'Overview',

    'Contributing',

    {
      type: 'category',
      label: '基础知识',
      items: [
        { type: 'autogenerated', dirName: 'Basic-Knowledge' }
      ],
    },
    {
      type: 'category',
      label: '前端',
      items: [
        { type: 'autogenerated', dirName: 'Front-End' }
      ]
    },
    {
      type: 'category',
      label: '后端',
      items: [
        { type: 'autogenerated', dirName: 'Back-End' }
      ]
    },
    {
      type: 'category',
      label: 'AI',
      items: [
        { type: 'autogenerated', dirName: 'AI' }
      ]
    },
    {
      type: 'category',
      label: '运维',
      items: [
        { type: 'autogenerated', dirName: 'Operation-and-Maintenance' }
      ]
    },
    {
      type: 'category',
      label: 'Hacking',
      items: [
        { type: 'autogenerated', dirName: 'Hacking' }
      ]
    },
    {
      type: 'category',
      label: '机器学习',
      items: [
        { type: 'autogenerated', dirName: 'Machine-Learning' }
      ]
    },
    {
      type: 'category',
      label: '量子计算',
      items: [
        { type: 'autogenerated', dirName: 'Quantum-Computing' }
      ]
    },
    {
      type: 'category',
      label: '其他',
      items: [
        { type: 'autogenerated', dirName: 'Other' }
      ]
    },
  ],
};

export default sidebars;
